### ISSUE TITLE
stepper 不支持传值和修改主题色

### ISSUE THREAD

**Issue by codesourse** [Alibaba-mp/mini-ali-ui#46]
## 背景
> stepper 不支持传值和修改主题色，自定义按钮

## 期望
> stepper 希望能支持传值和修改主题色，自定义按钮

## 思路
> 
建议加一个回调参数把this.props 里面的参数吐出来
主题色外面加个入口
加减按钮能自定义传入图片

辛苦辛苦各位大佬
谢谢

**Comment by linxz** [comment]
好的，对于你的意见我们会好好考虑一下，后续安排跟进。
如有兴趣，也可以提 pr 哦

**Comment by linxz** [comment]
主题色的相关配置，可以参考 https://github.com/Alibaba-mp/mini-ali-ui/blob/master/src/style/themes/default.less#L1183 中的 CSS 自定义属性来操作，比如在有 **stepper** 组件的页面中，加入，其中 `:root` 可以根据组件所在父级的 **className** 而改变。
```css
:root {
  /* color | 步进器加减按钮内容颜色 */
  --am-stepper-btn-color: red;
  /*.....*/
}
```

也可以直接通过 Devtools 查找到相对应元素的 **className**，然后写样式覆盖。比如；
```css
.am-stepper-add .am-icon {
  color: red;
}
```

至于回调参数和自定义传图，目前来看，不太好操作，暂时就先不处理了。
后续有改版的计划，到时候再好好规划一下，把这个历史产物调整一下。

目前给你带来的不便，十分抱歉。
